// Action Types
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_ERROR_CLEARED = 'SIGNUP_ERROR_CLEARED';
